#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# USER CONTROLLER ROUTES

user:
  path: /user
  controller: App\Controller\UserController::index
  methods: [POST]

create:
  path: /create
  controller: App\Controller\UserController::create
  methods: [POST]

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: [POST]

user_edit:
  path: /user/edit
  controller: App\Controller\UserController::edit
  methods: [POST]

# PROJECT CONTROLLER ROUTES

project:
  path: /project
  controller: App\Controller\ProjectController::index

project_new:
  path: /project/new
  controller: App\Controller\ProjectController::newProject
  methods: [POST]

project_edit:
  path: /project/edit/{id}
  controller: App\Controller\ProjectController::newProject
  methods: [PUT]

project_list:
  path: /project/list
  controller: App\Controller\ProjectController::projects
  methods: [GET]

project_detail:
  path: /project/detail/{id}
  controller: App\Controller\ProjectController::project
  methods: [GET]

project_remove:
  path: /project/remove/{id}
  controller: App\Controller\ProjectController::remove
  methods: [DELETE]
